### PR TITLE
Coveralls

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by tomwhite** [comment]
Not able to get coveralls to show the test coverage... seems to be a combination of tox, pytest, and travis not working with coverage/coveralls.

**Comment by laserson** [comment]
Possible that it needs to be merged into master before it works?

**Comment by tomwhite** [comment]
Coveralls is picking up the builds (e.g. https://coveralls.io/jobs/42960442), it's just that they have 0% or unknown coverage. Tox is interacting in an odd way, and nothing I've tried works!

**Comment by laserson** [comment]
Is it possible to ditch tox and use travis's build matrix mechanism?

**Comment by tomwhite** [comment]
Tox is used to provide different environments for Python 2 and 3. In particular, Beam only runs on Python 2, so the set up there is different. Scanpy is Python 3 only and [NumPy is only going to do Python 3 releases from January](https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html), so there is a case for dropping Python 2 anyway.

**Comment by tomwhite** [comment]
Weirdly this started working, so perhaps it was something to do with Coveralls not updating straight away. I've merged it now. I just noticed that the badge reports 69% coverage, even though when you click through the source file coverage is 83%.

**Pull request merged**
